<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListaVentas [ 
<!ELEMENT listaventa (venta)+>
<!ELEMENT venta (importe,comprador,vendedor,fecha?,codigofactura)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT vendedor (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT codigofactura (#PCDATA)>
]>


<ListaVentas>
    <venta>
        <importe>100</importe>
        <comprador>yo</comprador>
        <vendedor>tu</vendedor>
        <fecha>hoy</fecha>
        <codigofactura>12345</codigofactura>
    </venta>
</ListaVentas>





